### ISSUE TITLE
Port basic functionality in restart.

### ISSUE THREAD

**Issue by TranquilRock** [AndyDu01/AndroidScript#16]
For the first restart plan, we plan to achieve these goals:
1. Extract compiler details into resource files (maybe .json?)
2. Extract Block editor content into resource files
3. Restore basic functionality (BasicEditor in legacy version)

**Comment by Roamer1337** [comment]
For newcomers, we are sorry that this project is under active reconstruction.
The legacy code needs massive fixes, so we thus remove those release versions.

**Comment by TranquilRock** [comment]
All functionality verified :)
